a) Un modelo de regresión que le permita predecir cualquier variable de interés
en función a otras.
</b>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_excel('credittable.xlsx')
df=(pd.DataFrame(df))

# Convertir a float, manejando errores de conversión
num_cols = ['WC_TA', 'RE_TA', 'EBIT_TA', 'MVE_BVTD', 'S_TA']
df[num_cols] = df[num_cols].replace(',', '.', regex=True).astype(float)

# Definir variables predictoras y objetivo
X = df[['WC_TA', 'RE_TA', 'MVE_BVTD', 'S_TA', 'Industry']]  # Variables independientes
y = df['EBIT_TA']  # Variable objetivo

# Dividir en entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear y entrenar modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Predicciones
y_pred = modelo.predict(X_test)

# Evaluación del modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Error Cuadrático Medio (MSE): {mse:.4f}')
print(f'Coeficiente de Determinación (R²): {r2:.4f}')


Error Cuadrático Medio (MSE): 0.0001
Coeficiente de Determinación (R²): 0.9128


b) Un modelo de clasificación que le permita predecir el Rating en función al resto
de variables de interés.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

df = pd.read_excel('credittable.xlsx')

# Convertir valores numéricos correctamente
num_cols = ['WC_TA', 'RE_TA', 'EBIT_TA', 'MVE_BVTD', 'S_TA']
df[num_cols] = df[num_cols].replace(',', '.', regex=True).astype(float)

# Convertir la variable categórica 'Rating' en valores numéricos
le = LabelEncoder()
df['Rating'] = le.fit_transform(df['Rating'])

# Definir variables predictoras (X) y variable objetivo (y)
X = df[['WC_TA', 'RE_TA', 'EBIT_TA', 'MVE_BVTD', 'S_TA', 'Industry']]
y = df['Rating']

# Dividir los datos en conjunto de entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear y entrenar modelo de Regresión Logística
modelo = LogisticRegression(max_iter=500, multi_class='multinomial', solver='lbfgs')
modelo.fit(X_train, y_train)

# Predicciones
y_pred = modelo.predict(X_test)

# Evaluación del modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)

print(f'Exactitud del modelo: {accuracy:.4f}')
print('Matriz de Confusión:')
print(conf_matrix)
print('Reporte de Clasificación:')
print(class_report)
print('\nReporte de Clasificación:')
print(report)


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Exactitud del modelo: 0.7243
Matriz de Confusión:
[[ 73   8   0   0   0  34   0]
 [ 13  48  12   0   0   0   0]
 [  1   6 117   0   0   0   0]
 [  0   0   0  21  46   0   3]
 [  0   0   0   1 142  31   0]
 [ 16   0   0   0  39 153   0]
 [  0   0   0   7   0   0  16]]
Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.71      0.63      0.67       115
           1       0.77      0.66      0.71        73
           2       0.91      0.94      0.92       124
           3       0.72      0.30      0.42        70
           4       0.63      0.82      0.71       174
           5       0.70      0.74      0.72       208
           6       0.84      0.70      0.76        23

    accuracy                           0.72       787
   macro avg       0.75      0.68      0.70       787
weighted avg       0.73      0.72      0.72       787


Reporte de Clasificación:
              precision    recall  f1-score   support

           A       0.71    

d) El departamento comercial acaba de dar entrada a un nuevo cliente con una
serie de características. En función al modelo de clasificación elegido, ¿podría
otorgarle el Rating correspondiente? Las características son:

In [ ]:
# Creé un DataFrame con las características del nuevo cliente
nuevo_cliente = pd.DataFrame({
    'WC_TA': [0.01],  # Reemplazar con los valores reales
    'RE_TA': [0.12],
    'EBIT_TA': [0.04],
    'MVE_BVTD': [2.12],
    'S_TA': [0.45],
    'Industry': [9]
})

# Diccionario de equivalencias entre valores numéricos y categorías de Rating
rating_dict = {
    0: 'A',
    1: 'BB',
    2: 'BBB',
    3: 'B',
    4: 'CCC',
    5: 'CC',
    6: 'D'
}

# Predecir el rating del nuevo cliente
rating_predicho = modelo.predict(nuevo_cliente)[0]

# Convertir el resultado numérico a la categoría de Rating
rating_categorizado = rating_dict.get(rating_predicho, "Desconocido")

print(f'El Rating asignado al nuevo cliente es: {rating_categorizado}')


El Rating asignado al nuevo cliente es: A
